### ISSUE TITLE
[general api | usage reports] Disabled metrics, not part of the plan, are included in the response

### ISSUE THREAD

**Issue by g10** [3scale/3scale_ws_api_for_nodejs#34]
Metrics with a `max_value` of `0` (aka. disabled / no limit) that are not part of the plan, are included in the response.

No limit metrics that actually are part of the plan are filtered out correctly.

##### RESPONSE

```
<?xml version="1.0" encoding="UTF-8"?>
<status>
	<authorized>true</authorized>
	<plan>API Dev Sandbox</plan>
	<usage_reports>
		<usage_report metric="hits" period="day">
			<period_start>2016-03-30 00:00:00 +0000</period_start>
			<period_end>2016-03-31 00:00:00 +0000</period_end>
			<max_value>500</max_value>
			<current_value>0</current_value>
		</usage_report>
		<usage_report metric="customMetric" period="minute">
			<period_start>2016-03-30 04:53:00 +0000</period_start>
			<period_end>2016-03-30 04:54:00 +0000</period_end>
			<max_value>0</max_value>
			<current_value>0</current_value>
		</usage_report>
		<usage_report metric="customMetric2" period="minute">
			<period_start>2016-03-30 04:53:00 +0000</period_start>
			<period_end>2016-03-30 04:54:00 +0000</period_end>
			<max_value>0</max_value>
			<current_value>0</current_value>
		</usage_report>
		…
	</usage_reports>
</status>
```

Is there actually a more appropriate place to submit these kind of API bugs?

**Comment by vdel26** [comment]
@g10 yes, the `usage_reports` field in the response to authorize or authrep calls always contains all the metrics or methods for which there are any limits. 

The reasoning is that `usage_reports` contains all the possible rate limits that a request could trigger. That way it is easy for you to check which one or which ones have been reached whenever authorization is denied for a request.

Metrics that are disabled are considered internally as having a limit of 0 requests, that is why you see them there. It is useful to have them there since 

The best way to reach us for any product related questions or bug reports is to send us an email at support@3scale.net. Feel free to send us any questions to that address.

**Comment by g10** [comment]
tnx for the feedback, I'll take it to support
